"""Per-session accumulating workbook.

Each chat session produces a single derived workbook at
``outputs/session_<timestamp>.xlsx``. Each substantive analytical turn appends a
sheet (PR-1: every successful query turn becomes a new sheet; PR-2 introduces
the de-noising classifier that decides update-vs-new-vs-skip). The workbook is
rewritten atomically on every turn so a tab close or crash never loses progress.

Guarantees:
- The original uploaded workbook is never modified (same v0.1 guarantee).
- The LLM never writes to this workbook. Pandas builds the data; openpyxl
  saves it; the conclusion line is generated by a deterministic template.
- Sensitive columns (per ``core.privacy``) are redacted at write time.
- The session workbook is bound to one source by (file_name, schema_hash). A
  different upload triggers ``reset_for_new_source`` and opens a fresh file.
"""

from __future__ import annotations

import json
import os
import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font

from core import privacy
from core.query_engine import _build_mask


DEFAULT_OUTPUT_DIR = Path("outputs")
DEFAULT_AUDIT_PATH = Path("logs/audit_log.jsonl")

_SHEET_NAME_MAX = 31  # Excel limit


@dataclass
class SheetRecord:
    """One sheet in the session workbook."""

    name: str
    user_message: str
    operation: str
    filters: list[dict[str, Any]]
    sort: dict[str, Any]
    group_by: str
    row_count: int
    columns_shown: list[str]
    sensitive_redacted: list[str]
    conclusion: str
    created_at: str
    data: list[dict[str, Any]] = field(default_factory=list)


@dataclass
class TurnOutcome:
    """Result of record_turn: did this turn produce a sheet?"""

    action: str          # "created" | "skipped"
    sheet_name: str = ""
    reason: str = ""     # populated for "skipped"


@dataclass
class SessionWorkbook:
    """An accumulating derived workbook for one chat session."""

    source_file_name: str = ""
    schema_hash: str = ""
    output_dir: Path = field(default_factory=lambda: DEFAULT_OUTPUT_DIR)
    session_id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    started_at: str = field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))
    sheets: list[SheetRecord] = field(default_factory=list)
    _path: Path | None = None

    # ---- lifecycle ----------------------------------------------------------

    @property
    def path(self) -> Path:
        """Resolve the on-disk path for this session, lazy-creating once."""
        if self._path is None:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            candidate = self.output_dir / f"session_{ts}.xlsx"
            counter = 1
            while candidate.exists():
                candidate = self.output_dir / f"session_{ts}_{counter}.xlsx"
                counter += 1
            self._path = candidate
        return self._path

    def reset_for_new_source(self, *, source_file_name: str, schema_hash: str) -> None:
        """Bind this instance to a new source workbook and start a fresh file."""
        self.source_file_name = source_file_name
        self.schema_hash = schema_hash
        self.session_id = uuid.uuid4().hex[:12]
        self.started_at = datetime.now().isoformat(timespec="seconds")
        self.sheets = []
        self._path = None

    def is_bound_to(self, *, source_file_name: str, schema_hash: str) -> bool:
        return (
            self.source_file_name == source_file_name
            and self.schema_hash == schema_hash
        )

    # ---- recording ----------------------------------------------------------

    def record_turn(
        self,
        *,
        user_message: str,
        plan: dict[str, Any],
        result: Any,
        loaded_sheets: dict[str, pd.DataFrame],
        removed_columns: list[str] | None = None,
        audit_path: Path | None = None,
    ) -> TurnOutcome:
        """Append a sheet for this turn and atomically rewrite the workbook.

        PR-1 behavior: every successful query operation produces a new sheet.
        Returns ``TurnOutcome("created", sheet_name)`` on success, or
        ``TurnOutcome("skipped", reason=...)`` if the turn was not eligible.
        Also appends a metadata-only ``sheet_added`` entry to the audit log.
        """
        operation = getattr(result, "operation", None) or plan.get("operation") or ""
        if not operation:
            return TurnOutcome("skipped", reason="no_operation")

        sheet_name = self._allocate_sheet_name(plan)
        sheet_data, columns_shown, redacted = self._materialize_data(
            plan=plan, result=result, loaded_sheets=loaded_sheets, removed_columns=removed_columns or [],
        )
        row_count = getattr(result, "row_count", None)
        if row_count is None:
            row_count = len(sheet_data)
        conclusion = build_conclusion(plan=plan, result=result, row_count=row_count)

        record = SheetRecord(
            name=sheet_name,
            user_message=user_message or "",
            operation=operation,
            filters=list(plan.get("filters") or []),
            sort=dict(plan.get("sort") or {}),
            group_by=str(plan.get("group_by") or ""),
            row_count=int(row_count or 0),
            columns_shown=list(columns_shown),
            sensitive_redacted=list(redacted),
            conclusion=conclusion,
            created_at=datetime.now().isoformat(timespec="seconds"),
            data=sheet_data,
        )
        self.sheets.append(record)
        self.save()
        _append_audit_entry(
            audit_path=audit_path,
            session_id=self.session_id,
            source_file_name=self.source_file_name,
            schema_hash=self.schema_hash,
            workbook_path=str(self.path),
            record=record,
        )
        return TurnOutcome("created", sheet_name=sheet_name)

    def suppress_last_turn(self) -> bool:
        """Remove the most recently added sheet (used by [Don't save this])."""
        if not self.sheets:
            return False
        self.sheets.pop()
        self.save()
        return True

    # ---- introspection ------------------------------------------------------

    def list_sheets(self) -> list[dict[str, Any]]:
        return [
            {
                "name": s.name,
                "row_count": s.row_count,
                "operation": s.operation,
                "created_at": s.created_at,
                "sensitive_redacted": list(s.sensitive_redacted),
            }
            for s in self.sheets
        ]

    # ---- persistence --------------------------------------------------------

    def save(self) -> Path:
        """Atomically rewrite the workbook to disk and return its path."""
        target = self.path
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp = target.with_suffix(target.suffix + ".tmp")

        wb = Workbook()
        # The default sheet becomes the cover page.
        cover = wb.active
        cover.title = "Cover"
        _write_cover_sheet(cover, self)

        for record in self.sheets:
            ws = wb.create_sheet(title=_excel_safe_sheet_title(record.name))
            _write_data_sheet(ws, record)

        log_ws = wb.create_sheet(title="Session log")
        _write_session_log_sheet(log_ws, self)

        wb.save(tmp)
        os.replace(tmp, target)
        return target

    # ---- internals ----------------------------------------------------------

    def _allocate_sheet_name(self, plan: dict[str, Any]) -> str:
        base = auto_sheet_name(plan)
        existing = {s.name for s in self.sheets}
        name = base
        counter = 2
        while name in existing:
            name = f"{base} ({counter})"
            counter += 1
        return name

    def _materialize_data(
        self,
        *,
        plan: dict[str, Any],
        result: Any,
        loaded_sheets: dict[str, pd.DataFrame],
        removed_columns: list[str],
    ) -> tuple[list[dict[str, Any]], list[str], list[str]]:
        """Build the row data + visible columns + redacted columns for the sheet.

        For row-level operations (``filtered_preview``) we rerun the filter mask
        on the source DataFrame to capture the FULL selection (not the 10-row
        preview the user saw on screen). For aggregate operations we use the
        result table as-computed. Sensitive columns are redacted via the same
        ``core.privacy`` classifier the chat preview uses.
        """
        operation = plan.get("operation") or ""
        sheet_name = plan.get("sheet") or ""

        if operation == "filtered_preview" and sheet_name in loaded_sheets:
            frame = loaded_sheets[sheet_name]
            filters = plan.get("filters") or []
            filter_mode = (plan.get("filter_mode") or "all").lower()
            mask = _build_mask(frame, filters, filter_mode) if filters else None
            subset = frame.loc[mask] if mask is not None else frame
            subset = _apply_sort(subset, plan.get("sort") or {})
            rows = subset.to_dict(orient="records")
        else:
            rows = list(getattr(result, "table", []) or [])

        if not rows:
            return [], [], list(removed_columns)

        # Apply the user's column projection before redaction so the recorded
        # sheet matches what the chat result shows.
        select_columns = [
            c for c in (plan.get("select_columns") or []) if isinstance(c, str) and c
        ]
        if select_columns:
            kept = [c for c in select_columns if c in rows[0]]
            if kept:
                rows = [{c: row.get(c) for c in kept} for row in rows]

        all_columns = list(rows[0].keys())
        hidden = [c for c in all_columns if privacy.is_hidden_by_default(c)]
        if hidden:
            hidden_set = set(hidden)
            rows = [{k: v for k, v in row.items() if k not in hidden_set} for row in rows]
            redacted = list(dict.fromkeys(list(removed_columns) + hidden))
        else:
            redacted = list(removed_columns)
        visible_columns = [c for c in all_columns if c not in set(hidden)]
        return rows, visible_columns, redacted


# ---- helpers shared with tests --------------------------------------------


def auto_sheet_name(plan: dict[str, Any]) -> str:
    """Deterministic, human-readable sheet name from a validated plan."""
    operation = plan.get("operation") or ""
    filters = plan.get("filters") or []
    group_by = plan.get("group_by") or ""
    parts: list[str] = []

    if operation == "filtered_preview":
        parts.append(_filter_phrase(filters) or "All rows")
    elif operation.startswith("groupby_"):
        verb = {"groupby_count": "Count", "groupby_sum": "Sum", "groupby_average": "Average"}.get(operation, "Group")
        parts.append(f"{verb} by {group_by}" if group_by else verb)
        if filters:
            parts.append(f"({_filter_phrase(filters)})")
    elif operation == "average_column":
        parts.append("Average " + (plan.get("value_column") or "value"))
        if filters:
            parts.append(f"({_filter_phrase(filters)})")
    elif operation == "sum_column":
        parts.append("Sum " + (plan.get("value_column") or "value"))
        if filters:
            parts.append(f"({_filter_phrase(filters)})")
    elif operation == "count_rows":
        parts.append("Count")
        if filters:
            parts.append(f"({_filter_phrase(filters)})")
    elif operation == "count_unique":
        parts.append("Distinct " + (plan.get("value_column") or "values"))
    elif operation == "min_column":
        parts.append("Min " + (plan.get("value_column") or "value"))
    elif operation == "max_column":
        parts.append("Max " + (plan.get("value_column") or "value"))
    else:
        parts.append(operation.replace("_", " ").title() or "Result")

    name = " ".join(parts).strip()
    return name or "Result"


def build_conclusion(*, plan: dict[str, Any], result: Any, row_count: int | None) -> str:
    """Deterministic conclusion line (no LLM call)."""
    operation = (getattr(result, "operation", None) or plan.get("operation") or "").strip()
    filters = plan.get("filters") or []
    description = getattr(result, "description", "") or ""
    value = getattr(result, "value", None)

    if description:
        return description

    selection = _filter_phrase(filters)
    if operation == "filtered_preview":
        if selection:
            return f"{row_count or 0} rows match {selection}."
        return f"{row_count or 0} rows in selection."
    if operation == "count_rows":
        return f"{value if value is not None else (row_count or 0)} rows match {selection}." if selection \
            else f"{value if value is not None else (row_count or 0)} rows total."
    if operation in {"average_column", "sum_column", "min_column", "max_column"}:
        verb = {"average_column": "Average", "sum_column": "Sum",
                "min_column": "Minimum", "max_column": "Maximum"}[operation]
        col = plan.get("value_column") or ""
        suffix = f" for {selection}" if selection else ""
        return f"{verb} of {col}{suffix}: {value}."
    if operation.startswith("groupby_"):
        gb = plan.get("group_by") or ""
        suffix = f" for {selection}" if selection else ""
        return f"Breakdown by {gb}{suffix}."
    return f"{row_count or 0} rows."


def _filter_phrase(filters: list[dict[str, Any]] | None) -> str:
    if not filters:
        return ""
    parts: list[str] = []
    for condition in filters:
        column = condition.get("column", "")
        operator = condition.get("operator", "")
        value = condition.get("value")
        parts.append(_render_condition(column, operator, value))
    return " AND ".join(p for p in parts if p)


_OPERATOR_LABEL = {
    "equals": "=", "not_equals": "≠",
    "less_than": "<", "less_than_or_equal": "≤",
    "greater_than": ">", "greater_than_or_equal": "≥",
    "in": "in", "not_in": "not in",
    "contains": "contains", "starts_with": "starts with", "ends_with": "ends with",
    "is_missing": "is missing", "is_not_missing": "is present",
}


def _render_condition(column: str, operator: str, value: Any) -> str:
    label = _OPERATOR_LABEL.get(operator, operator or "=")
    if operator in {"is_missing", "is_not_missing"}:
        return f"{column} {label}".strip()
    if isinstance(value, list):
        rendered = ", ".join(str(v) for v in value)
        return f"{column} {label} [{rendered}]"
    return f"{column} {label} {value}"


def _apply_sort(frame: pd.DataFrame, sort: dict[str, Any]) -> pd.DataFrame:
    column = sort.get("column") if isinstance(sort, dict) else None
    if not column or column not in frame.columns:
        return frame
    direction = (sort.get("direction") or "asc").lower()
    ascending = direction != "desc"
    try:
        return frame.sort_values(by=column, ascending=ascending, kind="stable")
    except Exception:
        return frame


def _excel_safe_sheet_title(name: str) -> str:
    """Excel forbids `:\\/?*[]` in sheet titles and limits length to 31 chars."""
    cleaned = re.sub(r"[:\\/?*\[\]]", " ", name).strip()
    if not cleaned:
        cleaned = "Sheet"
    return cleaned[:_SHEET_NAME_MAX]


# ---- workbook writers -----------------------------------------------------


def _bold(cell) -> None:
    cell.font = Font(bold=True)


def _write_cover_sheet(ws, sw: "SessionWorkbook") -> None:
    ws["A1"] = "Dean session workbook"
    _bold(ws["A1"])
    ws["A2"] = f"Session ID: {sw.session_id}"
    ws["A3"] = f"Started: {sw.started_at}"
    ws["A4"] = f"Source workbook: {sw.source_file_name or '(unknown)'}"
    ws["A5"] = f"Source schema hash: {sw.schema_hash or '(unknown)'}"
    ws["A6"] = f"Sheets recorded: {len(sw.sheets)}"
    ws["A8"] = "Investigations"
    _bold(ws["A8"])
    ws["A9"] = "Sheet"
    ws["B9"] = "Operation"
    ws["C9"] = "Rows"
    ws["D9"] = "Created"
    for cell in (ws["A9"], ws["B9"], ws["C9"], ws["D9"]):
        _bold(cell)
    for i, record in enumerate(sw.sheets, start=10):
        ws.cell(row=i, column=1, value=record.name)
        ws.cell(row=i, column=2, value=record.operation)
        ws.cell(row=i, column=3, value=record.row_count)
        ws.cell(row=i, column=4, value=record.created_at)


def _write_data_sheet(ws, record: SheetRecord) -> None:
    """Write one investigation sheet: 5 header rows, blank, then the data table."""
    ws["A1"] = f"Investigation: {record.name}"
    _bold(ws["A1"])
    ws["A2"] = f"Question: {record.user_message}"
    ws["A3"] = f"Filters: {_filter_phrase(record.filters) or '(none)'}"
    sort_text = ""
    if record.sort and record.sort.get("column"):
        sort_text = f"Sort: {record.sort.get('column')} {record.sort.get('direction') or 'asc'}"
    hidden_text = "Hidden: " + (", ".join(record.sensitive_redacted) if record.sensitive_redacted else "—")
    extras = " · ".join(p for p in (sort_text, f"Rows: {record.row_count}", hidden_text) if p)
    ws["A4"] = extras
    ws["A5"] = f"Conclusion: {record.conclusion}"
    # Row 6 is blank — visual separator before the data table.

    columns = record.columns_shown or (list(record.data[0].keys()) if record.data else [])
    if not columns:
        ws["A7"] = "(no rows)"
        return

    for col_index, column in enumerate(columns, start=1):
        cell = ws.cell(row=7, column=col_index, value=column)
        _bold(cell)
    for row_index, row in enumerate(record.data, start=8):
        for col_index, column in enumerate(columns, start=1):
            ws.cell(row=row_index, column=col_index, value=row.get(column))


def _write_session_log_sheet(ws, sw: "SessionWorkbook") -> None:
    ws["A1"] = "Session log"
    _bold(ws["A1"])
    headers = ["#", "Sheet", "Question", "Operation", "Filters", "Rows", "Created"]
    for i, header in enumerate(headers, start=1):
        cell = ws.cell(row=2, column=i, value=header)
        _bold(cell)
    for i, record in enumerate(sw.sheets, start=3):
        ws.cell(row=i, column=1, value=i - 2)
        ws.cell(row=i, column=2, value=record.name)
        ws.cell(row=i, column=3, value=record.user_message)
        ws.cell(row=i, column=4, value=record.operation)
        ws.cell(row=i, column=5, value=_filter_phrase(record.filters))
        ws.cell(row=i, column=6, value=record.row_count)
        ws.cell(row=i, column=7, value=record.created_at)


# ---- audit-log integration ------------------------------------------------


def _append_audit_entry(
    *,
    audit_path: Path | None,
    session_id: str,
    source_file_name: str,
    schema_hash: str,
    workbook_path: str,
    record: SheetRecord,
) -> None:
    """Append one metadata-only sheet_added entry to the audit log."""
    target = Path(audit_path or DEFAULT_AUDIT_PATH)
    target.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": record.created_at,
        "action_type": "sheet_added",
        "session_id": session_id,
        "source_workbook": source_file_name,
        "source_schema_hash": schema_hash,
        "session_workbook": workbook_path,
        "sheet_name": record.name,
        "operation": record.operation,
        "filters_applied": record.filters,
        "rows_affected": record.row_count,
        "columns_shown": record.columns_shown,
        "sensitive_fields_redacted": record.sensitive_redacted,
        "confirmation_status": "auto_saved",
    }
    with target.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(entry) + "\n")
